- name: Install Jenkins
  hosts: master1
  gather_facts: false
  become: true
  tasks:
    - name: Create a Deployment by reading the definition from a local file
      shell: kubectl apply -f http://210.179.249.40:8090/kcs-final/argocd/namespace.yaml

    - name: Create a Deployment by reading the definition from a local file
      shell: kubectl apply -f http://210.179.249.40:8090/kcs-final/argocd/argocd.yaml -n argocd
