- name: Install MongoDB
  hosts: master1
  gather_facts: false
  become: true
  tasks:
    - name: Download MongoDB User
      get_url:
        url: http://www.eg-playground.xyz:8090/kcs-final/database/mongodb-user.yaml
        dest: /root/mongodb-user.yaml
        mode: "0755"

    - name: Download MongoDB File Server
      get_url:
        url: http://www.eg-playground.xyz:8090/kcs-final/database/mongodb-fs.yaml
        dest: /root/mongodb-fs.yaml
        mode: "0755"
    - name: Download MongoDB Post
      get_url:
        url: http://www.eg-playground.xyz:8090/kcs-final/database/mongodb-post.yaml
        dest: /root/mongodb-post.yaml
        mode: "0755"

    - name: Set MongoDB NFS Address
      replace:
        path: "{{ item }}"
        regexp: '\[\[(.*?)\]\]'
        replace: "{{ NFS_IP }}"
      with_items:
        [
          "/root/mongodb-user.yaml",
          "/root/mongodb-fs.yaml",
          "/root/mongodb-post.yaml"
        ]

    - name: Deploy MongoDB Resource
      shell:
        cmd: sudo kubectl apply -f http://www.eg-playground.xyz:8090/kcs-final/database/mongodb-resource.yaml

    - name: Deploy MongoDB
      shell:
        cmd: sudo kubectl apply -f {{ item }}
      with_items:
        [
          "/root/mongodb-user.yaml",
          "/root/mongodb-fs.yaml",
          "/root/mongodb-post.yaml"
        ]
