- name: Kubeadm Install Components
  hosts: master1
  gather_facts: false
  become: true
  tasks:
    - name: Install CNI and MetalLB
      shell: |
        sudo kubectl apply -f http://210.179.249.40:8090/kcs-final/tigera-operator.yaml
        sudo kubectl apply -f http://210.179.249.40:8090/kcs-final/custom-resources.yaml

        echo "sleep 3 secs..."
        sleep 3

        echo "setting metallb..."

        sudo kubectl apply -f http://210.179.249.40:8090/kcs-final/metallb-namespace.yaml
        sudo kubectl apply -f http://210.179.249.40:8090/kcs-final/metallb.yaml
        sudo kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"


        echo "sleep 1 sec..."
        sleep 1
