- name: Create and Start VM
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Define VM
      command: >
        virt-install --import --name {{ GUEST_NAME }}
        --memory 2048 --vcpus 1 --noautoconsole
        --os-variant ubuntu22.04 --hvm --network bridge=br0,mac={{ FLOAT_MAC_ADDR }}
        --network network=default,mac={{ PRIV_MAC_ADDR }}
        --disk=/vm-images/{{ GUEST_NAME }}.img --import
    - name: Ensure VM is started
      virt:
        name: "{{ GUEST_NAME }}"
        state: running
      register: vm_start_results
      until: "vm_start_results is success"
      retries: 15
      delay: 2

- name: Add Host to Ansible Inventory
  hosts: localhost
  become: true
  tasks:
    - name: Get IP Address
      shell: virsh domifaddr {{ GUEST_NAME }} | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b'
      register: defined_vm_ip_result
      until: "defined_vm_ip_result is success"
      retries: 30
      delay: 5

    - name: Set IP Address
      set_fact:
        vm_ip: "{{ item }}"
      with_items: "{{ defined_vm_ip_result.stdout }}"

    - name: Set Host
      blockinfile:
        create: true
        path: "{{ INVENTORY_PATH }}"
        block: |
          [{{ GUEST_NAME }}]
          root@{{ vm_ip }} ansible_ssh_pass=test123 ansible_ssh_common_args= '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
