- name: Get Private IP
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Get Private IP Address
      shell: virsh domifaddr {{ GUEST_NAME }} | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b'
      register: defined_vm_ip_result
      until: "defined_vm_ip_result is success"
      retries: 30
      delay: 5
