- name: Get Private IP
  hosts: localhost
  become: true
  tasks:
    - name: Get IP Address
      shell: virsh domifaddr {{ GUEST_NAME }} | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b'
      register: defined_vm_ip_result
      until: "defined_vm_ip_result is success"
      retries: 30
      delay: 5

- name: Get Floating IP
  hosts: "{{ GUEST_NAME }}"
  become: true
  tasks:
    - name: Get Floating IP
      shell: ip a | grep 192.168.50 | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b'
      register: floating_ip
    
