- name: Set VM Hostname And Reboot
  hosts: "{{ GUEST_NAME }}"
  gather_facts: false
  become: true
  tasks:
    - name: Set Hostname
      shell:
        cmd: sudo echo "{{ GUEST_NAME }}" > /etc/hostname
