- name: Set VM Floating IP
  hosts: "{{ GUEST_NAME }}"
  gather_facts: false
  become: true
  tasks:
    - name: Set Floating IP
      lineinfile:
        path: /etc/netplan/50-cloud-init.yaml
        state: present
        regexp: "dhcp4: no"
        line: "      dhcp4: yes"

    - name: Sleep
      shell: sleep 1

    - name: Ensure Set Floating IP
      lineinfile:
        path: /etc/netplan/50-cloud-init.yaml
        state: present
        regexp: "dhcp4: no"
        line: "      dhcp4: yes"

    - name: Netplan Apply
      shell: sudo netplan apply
